# Generated by Django 5.2.9 on 2025-12-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AICapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="AI-kapacitet")),
            ],
            options={
                "verbose_name": "AI-kapacitet",
                "verbose_name_plural": "AI-kapaciteter",
                "db_table": "ai_capabilities",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Företagsnamn")),
                (
                    "website",
                    models.TextField(blank=True, null=True, verbose_name="Webbplats"),
                ),
                ("type", models.TextField(blank=True, null=True, verbose_name="Typ")),
                (
                    "logo_url",
                    models.TextField(blank=True, null=True, verbose_name="Logotyp URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Beskrivning"),
                ),
                (
                    "owner",
                    models.TextField(blank=True, null=True, verbose_name="Ägare"),
                ),
                (
                    "location_city",
                    models.TextField(blank=True, null=True, verbose_name="Stad"),
                ),
                (
                    "location_greater_stockholm",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Stor-Stockholm"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Senast uppdaterad"
                    ),
                ),
                (
                    "data_quality_score",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Datakvalitet"
                    ),
                ),
                (
                    "source_url",
                    models.TextField(blank=True, null=True, verbose_name="Käll-URL"),
                ),
                (
                    "sector_vec_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sector Vec 1"
                    ),
                ),
                (
                    "sector_vec_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sector Vec 2"
                    ),
                ),
                (
                    "type_new",
                    models.TextField(blank=True, null=True, verbose_name="Type New"),
                ),
                (
                    "description_new",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description New"
                    ),
                ),
                (
                    "ai_capabilities_new",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ai Capabilities New"
                    ),
                ),
                (
                    "sector_1_new",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sector 1 New"
                    ),
                ),
                (
                    "sector_2_new",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sector 2 New"
                    ),
                ),
                (
                    "confidence_newdata",
                    models.TextField(
                        blank=True, null=True, verbose_name="Confidence Newdata"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI-företag",
                "verbose_name_plural": "AI-företag",
                "db_table": "companies",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Dimension")),
            ],
            options={
                "verbose_name": "Dimension",
                "verbose_name_plural": "Dimensioner",
                "db_table": "dimensions",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Domän")),
            ],
            options={
                "verbose_name": "Domän",
                "verbose_name_plural": "Domäner",
                "db_table": "domains",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SCBMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matched", models.IntegerField(verbose_name="Matchad")),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Poäng"),
                ),
                ("city", models.TextField(blank=True, null=True, verbose_name="Stad")),
                (
                    "payload",
                    models.TextField(blank=True, null=True, verbose_name="Data"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
            ],
            options={
                "verbose_name": "SCB-matchning",
                "verbose_name_plural": "SCB-matchningar",
                "db_table": "scb_matches",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True, verbose_name="Sektor")),
            ],
            options={
                "verbose_name": "Sektor",
                "verbose_name_plural": "Sektorer",
                "db_table": "sectors",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AICompany",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "NAMN",
                    models.TextField(
                        blank=True, null=True, verbose_name="Företagsnamn"
                    ),
                ),
                (
                    "SAJT",
                    models.TextField(blank=True, null=True, verbose_name="Webbplats"),
                ),
                (
                    "BESKRIVNING",
                    models.TextField(blank=True, null=True, verbose_name="Beskrivning"),
                ),
                ("STAD", models.TextField(blank=True, null=True, verbose_name="Stad")),
                (
                    "STORSTOCKHOLM",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Stor-Stockholm"
                    ),
                ),
                (
                    "URL_LOGOTYP",
                    models.TextField(blank=True, null=True, verbose_name="URL Logotyp"),
                ),
                (
                    "URL_KÄLLA",
                    models.TextField(
                        blank=True,
                        db_column="URL_KÄLLA",
                        null=True,
                        verbose_name="URL Källa",
                    ),
                ),
                (
                    "BRANSCHKLUSTER_LITEN",
                    models.TextField(
                        blank=True, null=True, verbose_name="Branschkluster Liten"
                    ),
                ),
                (
                    "BRANSCHKLUSTER_STOR",
                    models.TextField(
                        blank=True, null=True, verbose_name="Branschkluster Stor"
                    ),
                ),
                (
                    "SEKTOR_SEMANTISK_MODELL",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sektor (Semantisk Modell)"
                    ),
                ),
                (
                    "SEKTOR_DETERMINISTISK_MODELL_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sektor (Deterministisk 1)"
                    ),
                ),
                (
                    "SEKTOR_DETERMINISTISK_MODELL_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sektor (Deterministisk 2)"
                    ),
                ),
                (
                    "SEKTOR_GAMMAL",
                    models.TextField(
                        blank=True, null=True, verbose_name="Sektor (Gammal)"
                    ),
                ),
                (
                    "AI_FÖRMÅGA_V2",
                    models.TextField(
                        blank=True,
                        db_column="AI-FÖRMÅGA_V2",
                        null=True,
                        verbose_name="AI-förmåga V2",
                    ),
                ),
                (
                    "BRANSCHKLUSTER_V2",
                    models.TextField(
                        blank=True, null=True, verbose_name="Branschkluster V2"
                    ),
                ),
                (
                    "ANSTÄLLDA_GRUPPERING_V2",
                    models.TextField(
                        blank=True,
                        db_column="ANSTÄLLDA_GRUPPERING_V2",
                        null=True,
                        verbose_name="Anställda gruppering V2",
                    ),
                ),
                (
                    "OMSÄTTNING_GRUPPERING_V2",
                    models.TextField(
                        blank=True,
                        db_column="OMSÄTTNING_GRUPPERING_V2",
                        null=True,
                        verbose_name="Omsättning gruppering V2",
                    ),
                ),
                (
                    "AI_FÖRMÅGA_SEMANTISK_MODELL",
                    models.TextField(
                        blank=True,
                        db_column="AI-FÖRMÅGA_SEMANTISK_MODELL",
                        null=True,
                        verbose_name="AI-förmåga (Semantisk Modell)",
                    ),
                ),
                (
                    "AI_FÖRMÅGA_GAMMAL",
                    models.TextField(
                        blank=True,
                        db_column="AI-FÖRMÅGA_GAMMAL",
                        null=True,
                        verbose_name="AI-förmåga (Gammal)",
                    ),
                ),
                (
                    "KONFIDENS_SEMANTISK_MODELL",
                    models.TextField(
                        blank=True, null=True, verbose_name="Konfidens (Semantisk)"
                    ),
                ),
                (
                    "ORGANISATIONSTYP_GAMMAL",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organisationstyp (Gammal)"
                    ),
                ),
                (
                    "SCB_ORGNR",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Organisationsnummer"
                    ),
                ),
                (
                    "SCB_NAMN",
                    models.TextField(blank=True, null=True, verbose_name="SCB Namn"),
                ),
                (
                    "SCB_ADRESS",
                    models.TextField(blank=True, null=True, verbose_name="SCB Adress"),
                ),
                (
                    "SCB_POSTNR",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Postnummer"
                    ),
                ),
                (
                    "SCB_STAD",
                    models.TextField(blank=True, null=True, verbose_name="SCB Stad"),
                ),
                (
                    "SCB_KONTOR",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Antal kontor"
                    ),
                ),
                (
                    "SCB_ANSTÄLLDA",
                    models.TextField(
                        blank=True,
                        db_column="SCB_ANSTÄLLDA",
                        null=True,
                        verbose_name="SCB Antal anställda",
                    ),
                ),
                (
                    "SCB_VERKSAMHETSSTATUS",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Verksamhetsstatus"
                    ),
                ),
                (
                    "SCB_JURIDISK_FORM",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Juridisk form"
                    ),
                ),
                (
                    "SCB_STARTDATUM",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Startdatum"
                    ),
                ),
                (
                    "SCB_REGISTRERINGSDATUM",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Registreringsdatum"
                    ),
                ),
                (
                    "SCB_BRANSCH_1",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Bransch 1"
                    ),
                ),
                (
                    "SCB_BRANSCH_2",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Bransch 2"
                    ),
                ),
                (
                    "SCB_OMSÄTTNING_ÅR",
                    models.TextField(
                        blank=True,
                        db_column="SCB_OMSÄTTNING_ÅR",
                        null=True,
                        verbose_name="SCB Omsättningsår",
                    ),
                ),
                (
                    "SCB_OMSÄTTNING_STORLEK",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Omsättning storlek"
                    ),
                ),
                (
                    "SCB_TEL",
                    models.TextField(blank=True, null=True, verbose_name="SCB Telefon"),
                ),
                (
                    "SCB_MAIL",
                    models.TextField(blank=True, null=True, verbose_name="SCB E-post"),
                ),
                (
                    "SCB_ARBETSGIVARE_STATUS",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Arbetsgivare status"
                    ),
                ),
                (
                    "SCB_FÖRETAGSÅLDER",
                    models.TextField(
                        blank=True,
                        db_column="SCB_FÖRETAGSÅLDER",
                        null=True,
                        verbose_name="SCB Företagsålder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Företagsdatabas",
                "verbose_name_plural": "Företagsdatabas",
                "db_table": "ai_companies",
                "ordering": ["NAMN"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PublicViewConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(
                        choices=[
                            ("name", "Företag"),
                            ("bransch", "Bransch"),
                            ("website", "Webbplats"),
                            ("description", "Beskrivning"),
                            ("location_city", "Stad"),
                            ("location_greater_stockholm", "Stor-Stockholm"),
                            ("logo_url", "Logotyp URL"),
                            ("source_url", "Käll-URL"),
                            ("organization_number", "Organisationsnummer"),
                            ("municipality", "Kommun"),
                            ("employee_size", "Antal anställda"),
                            ("legal_form", "Juridisk form"),
                            ("industry_1", "Bransch 1"),
                            ("industry_2", "Bransch 2"),
                            ("phone", "Telefon"),
                            ("email", "E-post"),
                            ("sectors", "Område"),
                            ("ai_capabilities", "AI-inriktning"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Kolumn",
                    ),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        help_text="Valfritt: Anpassat namn som visas i den publika vyn. Lämna tomt för att använda standardnamnet.",
                        max_length=100,
                        null=True,
                        verbose_name="Anpassad etikett",
                    ),
                ),
                (
                    "show_on_desktop",
                    models.BooleanField(default=True, verbose_name="Visa på desktop"),
                ),
                (
                    "show_on_mobile",
                    models.BooleanField(default=False, verbose_name="Visa på mobil"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Visningsordning"),
                ),
            ],
            options={
                "verbose_name": "Publik vy - kolumnkonfiguration",
                "verbose_name_plural": "Publik vy - kolumnkonfigurationer",
                "ordering": ["display_order", "column_name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAICapability",
            fields=[
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_ai_capabilities",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyDimension",
            fields=[
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_dimensions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyDomain",
            fields=[
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_domains",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CompanySector",
            fields=[
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_sectors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SCBEnrichment",
            fields=[
                (
                    "company",
                    models.OneToOneField(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="scb_enrichment",
                        serialize=False,
                        to="companies.company",
                        verbose_name="Företag",
                    ),
                ),
                (
                    "organization_number",
                    models.TextField(
                        blank=True, null=True, verbose_name="Organisationsnummer"
                    ),
                ),
                (
                    "scb_company_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="SCB Företagsnamn"
                    ),
                ),
                (
                    "co_address",
                    models.TextField(blank=True, null=True, verbose_name="C/O Adress"),
                ),
                (
                    "post_address",
                    models.TextField(blank=True, null=True, verbose_name="Postadress"),
                ),
                (
                    "post_code",
                    models.TextField(blank=True, null=True, verbose_name="Postnummer"),
                ),
                (
                    "post_city",
                    models.TextField(blank=True, null=True, verbose_name="Postort"),
                ),
                (
                    "municipality_code",
                    models.TextField(blank=True, null=True, verbose_name="Kommunkod"),
                ),
                (
                    "municipality",
                    models.TextField(blank=True, null=True, verbose_name="Kommun"),
                ),
                (
                    "county_code",
                    models.TextField(blank=True, null=True, verbose_name="Länskod"),
                ),
                ("county", models.TextField(blank=True, null=True, verbose_name="Län")),
                (
                    "num_workplaces",
                    models.TextField(
                        blank=True, null=True, verbose_name="Antal arbetsplatser"
                    ),
                ),
                (
                    "employee_size_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Anställningskod"
                    ),
                ),
                (
                    "employee_size",
                    models.TextField(
                        blank=True, null=True, verbose_name="Antal anställda"
                    ),
                ),
                (
                    "company_status_code",
                    models.TextField(blank=True, null=True, verbose_name="Statuskod"),
                ),
                (
                    "company_status",
                    models.TextField(blank=True, null=True, verbose_name="Status"),
                ),
                (
                    "legal_form_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Juridisk form kod"
                    ),
                ),
                (
                    "legal_form",
                    models.TextField(
                        blank=True, null=True, verbose_name="Juridisk form"
                    ),
                ),
                (
                    "start_date",
                    models.TextField(blank=True, null=True, verbose_name="Startdatum"),
                ),
                (
                    "registration_date",
                    models.TextField(
                        blank=True, null=True, verbose_name="Registreringsdatum"
                    ),
                ),
                (
                    "industry_1_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Branschkod 1"
                    ),
                ),
                (
                    "industry_1",
                    models.TextField(blank=True, null=True, verbose_name="Bransch 1"),
                ),
                (
                    "industry_2_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Branschkod 2"
                    ),
                ),
                (
                    "industry_2",
                    models.TextField(blank=True, null=True, verbose_name="Bransch 2"),
                ),
                (
                    "revenue_year",
                    models.TextField(
                        blank=True, null=True, verbose_name="Omsättningsår"
                    ),
                ),
                (
                    "revenue_size_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Omsättningskod"
                    ),
                ),
                (
                    "revenue_size",
                    models.TextField(blank=True, null=True, verbose_name="Omsättning"),
                ),
                (
                    "phone",
                    models.TextField(blank=True, null=True, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.TextField(blank=True, null=True, verbose_name="E-post"),
                ),
                (
                    "employer_status_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Arbetsgivarstatuskod"
                    ),
                ),
                (
                    "employer_status",
                    models.TextField(
                        blank=True, null=True, verbose_name="Arbetsgivarstatus"
                    ),
                ),
                (
                    "vat_status_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Momsstatuskod"
                    ),
                ),
                (
                    "vat_status",
                    models.TextField(blank=True, null=True, verbose_name="Momsstatus"),
                ),
                (
                    "export_import",
                    models.TextField(
                        blank=True, null=True, verbose_name="Export/Import"
                    ),
                ),
            ],
            options={
                "verbose_name": "SCB-anrikning",
                "verbose_name_plural": "SCB-anrikningar",
                "db_table": "scb_enrichment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ErrorReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("incorrect_info", "Felaktig information"),
                            ("company_not_exist", "Företaget finns ej"),
                            ("missing_data", "Saknad data"),
                            ("suggestion_new_company", "Förslag på nytt företag"),
                            ("other", "Annat"),
                        ],
                        max_length=50,
                        verbose_name="Typ av fel",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Ämne")),
                ("description", models.TextField(verbose_name="Beskrivning")),
                (
                    "suggestion",
                    models.TextField(blank=True, verbose_name="Förslag på korrigering"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Väntar"),
                            ("in_progress", "Under granskning"),
                            ("resolved", "Hanterad"),
                            ("rejected", "Avvisad"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Skapad"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Uppdaterad"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin-anteckningar"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null för företagsförslag",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_reports",
                        to="companies.aicompany",
                        verbose_name="Företag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Felanmälan",
                "verbose_name_plural": "Felanmälningar",
                "db_table": "error_reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
