# Generated by Django 5.2.8 on 2025-12-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='resolved',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Admin-anteckningar'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='error_type',
            field=models.CharField(choices=[('incorrect_info', 'Felaktig information'), ('company_not_exist', 'Företaget finns ej'), ('missing_data', 'Saknad data'), ('other', 'Annat')], default='other', max_length=50, verbose_name='Typ av fel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Väntar'), ('in_progress', 'Under granskning'), ('resolved', 'Hanterad'), ('rejected', 'Avvisad')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='suggestion',
            field=models.TextField(blank=True, verbose_name='Förslag på korrigering'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Uppdaterad'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='companies.aicompany', verbose_name='Företag'),
        ),
        migrations.AlterField(
            model_name='publicviewconfiguration',
            name='column_name',
            field=models.CharField(choices=[('name', 'Företag'), ('bransch', 'Bransch'), ('website', 'Webbplats'), ('description', 'Beskrivning'), ('location_city', 'Stad'), ('location_greater_stockholm', 'Stor-Stockholm'), ('logo_url', 'Logotyp URL'), ('source_url', 'Käll-URL'), ('organization_number', 'Organisationsnummer'), ('municipality', 'Kommun'), ('employee_size', 'Antal anställda'), ('legal_form', 'Juridisk form'), ('industry_1', 'Bransch 1'), ('industry_2', 'Bransch 2'), ('phone', 'Telefon'), ('email', 'E-post'), ('sectors', 'Område'), ('ai_capabilities', 'AI-typ')], max_length=50, unique=True, verbose_name='Kolumn'),
        ),
    ]
