# Generated by Django 5.2.9 on 2025-12-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aicompany",
            name="AI_FÖRMÅGA_GAMMAL",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="AI_FÖRMÅGA_SEMANTISK_MODELL",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="BRANSCHKLUSTER_LITEN",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="BRANSCHKLUSTER_STOR",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="KONFIDENS_SEMANTISK_MODELL",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="ORGANISATIONSTYP_GAMMAL",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="SEKTOR_DETERMINISTISK_MODELL_1",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="SEKTOR_DETERMINISTISK_MODELL_2",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="SEKTOR_GAMMAL",
        ),
        migrations.RemoveField(
            model_name="aicompany",
            name="SEKTOR_SEMANTISK_MODELL",
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_INFRASTRUKTUR_DATA",
            field=models.BooleanField(
                blank=True,
                db_column="Infrastruktur & Data",
                default=False,
                null=True,
                verbose_name="Infrastruktur & Data",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_INSIKT_ANALYS",
            field=models.BooleanField(
                blank=True,
                db_column="Insikt & Analys",
                default=False,
                null=True,
                verbose_name="Insikt & Analys",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_OPTIMERING_AUTOMATION",
            field=models.BooleanField(
                blank=True,
                db_column="Optimering & Automation",
                default=False,
                null=True,
                verbose_name="Optimering & Automation",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_PROGNOS_PREDIKTION",
            field=models.BooleanField(
                blank=True,
                db_column="Prognos & Prediktion",
                default=False,
                null=True,
                verbose_name="Prognos & Prediktion",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_SPRAK_LJUD",
            field=models.BooleanField(
                blank=True,
                db_column="Språk & Ljud",
                default=False,
                null=True,
                verbose_name="Språk & Ljud",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="TILLAMPNING_VISUELL_AI",
            field=models.BooleanField(
                blank=True,
                db_column="Visuell AI",
                default=False,
                null=True,
                verbose_name="Visuell AI",
            ),
        ),
    ]
