# Generated by Django 5.2.8 on 2025-12-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_errorreport_resolved_errorreport_admin_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicompany',
            options={'managed': True, 'ordering': ['NAMN'], 'verbose_name': 'Företagsdatabas', 'verbose_name_plural': 'Företagsdatabas'},
        ),
    ]
