# Generated by Django 5.2.8 on 2025-12-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_aicompany_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicompany',
            name='AI_FÖRMÅGA_V2',
            field=models.TextField(blank=True, db_column='AI-FÖRMÅGA_V2', null=True, verbose_name='AI-förmåga V2'),
        ),
        migrations.AddField(
            model_name='aicompany',
            name='BRANSCHKLUSTER_V2',
            field=models.TextField(blank=True, null=True, verbose_name='Branschkluster V2'),
        ),
    ]
