# Generated by Django 5.2.9 on 2025-12-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_aicompany_ai_förmåga_v2_aicompany_branschkluster_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="aicompany",
            name="ANSTÄLLDA_GRUPPERING_V2",
            field=models.TextField(
                blank=True,
                db_column="ANSTÄLLDA_GRUPPERING_V2",
                null=True,
                verbose_name="Anställda gruppering V2",
            ),
        ),
        migrations.AddField(
            model_name="aicompany",
            name="OMSÄTTNING_GRUPPERING_V2",
            field=models.TextField(
                blank=True,
                db_column="OMSÄTTNING_GRUPPERING_V2",
                null=True,
                verbose_name="Omsättning gruppering V2",
            ),
        ),
        migrations.AlterField(
            model_name="publicviewconfiguration",
            name="column_name",
            field=models.CharField(
                choices=[
                    ("name", "Företag"),
                    ("bransch", "Bransch"),
                    ("website", "Webbplats"),
                    ("description", "Beskrivning"),
                    ("location_city", "Stad"),
                    ("location_greater_stockholm", "Stor-Stockholm"),
                    ("logo_url", "Logotyp URL"),
                    ("source_url", "Käll-URL"),
                    ("organization_number", "Organisationsnummer"),
                    ("municipality", "Kommun"),
                    ("employee_size", "Antal anställda"),
                    ("legal_form", "Juridisk form"),
                    ("industry_1", "Bransch 1"),
                    ("industry_2", "Bransch 2"),
                    ("phone", "Telefon"),
                    ("email", "E-post"),
                    ("sectors", "Område"),
                    ("ai_capabilities", "AI-inriktning"),
                ],
                max_length=50,
                unique=True,
                verbose_name="Kolumn",
            ),
        ),
    ]
