# Generated by Django 5.2.9 on 2025-12-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_aicompany_anställda_gruppering_v2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorreport",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Null för företagsförslag",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="error_reports",
                to="companies.aicompany",
                verbose_name="Företag",
            ),
        ),
        migrations.AlterField(
            model_name="errorreport",
            name="error_type",
            field=models.CharField(
                choices=[
                    ("incorrect_info", "Felaktig information"),
                    ("company_not_exist", "Företaget finns ej"),
                    ("missing_data", "Saknad data"),
                    ("suggestion_new_company", "Förslag på nytt företag"),
                    ("other", "Annat"),
                ],
                max_length=50,
                verbose_name="Typ av fel",
            ),
        ),
    ]
